# Generated by Django 5.1.3 on 2025-01-20 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='App',
            new_name='Recipes',
        ),
    ]
