# Generated by Django 5.1.3 on 2025-01-23 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_rename_app_recipes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_machine_failure', models.DateField(verbose_name='Дата отказа')),
                ('operating_time', models.IntegerField(verbose_name='Наработка, м/час')),
                ('description_machine_failure', models.TextField(verbose_name='Описание отказа')),
                ('used_spare_parts', models.TextField(blank=True, null=True, verbose_name='Используемые запасные части')),
                ('date_restoration', models.DateField(verbose_name='Дата восстановления')),
                ('machine_downtime', models.IntegerField(editable=False, verbose_name='Время простоя техники')),
            ],
            options={
                'verbose_name': 'Рекламация',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_number', models.CharField(max_length=16, unique=True, verbose_name='Зав. № машины')),
                ('engine_factory_num', models.CharField(max_length=16, unique=True, verbose_name='Зав. № двигателя')),
                ('factory_num_transmission', models.CharField(max_length=16, unique=True, verbose_name='Зав. № трансмиссии')),
                ('factory_num_drive_axle', models.CharField(max_length=16, unique=True, verbose_name='Зав. № ведущего моста')),
                ('factory_num_guiding_bridge', models.CharField(max_length=16, unique=True, verbose_name='Зав. № управляемого моста')),
                ('delivery_agreement', models.CharField(max_length=16, unique=True, verbose_name='Договор поставки №, дата')),
                ('date_shipment_factory', models.DateField(verbose_name='Дата отгрузки с завода')),
                ('consignee', models.CharField(max_length=128, verbose_name='Грузополучатель (конечный потребитель)')),
                ('shipping_address', models.CharField(max_length=256, verbose_name='Адрес поставки (эксплуатации)')),
                ('equipment', models.TextField(verbose_name='Комплектация (доп. опции)')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Машина',
            },
        ),
        migrations.CreateModel(
            name='ReferenceBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_type', models.CharField(max_length=128, verbose_name='Тип справочника')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Cправочник',
                'unique_together': {('reference_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ServiceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.CharField(max_length=128, verbose_name='Название компании')),
                ('description', models.TextField(verbose_name='Описание')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TechMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_maintenance', models.DateField(verbose_name='Дата проведения ТО')),
                ('operating_time', models.IntegerField(verbose_name='Наработка, м/час')),
                ('order_number', models.CharField(max_length=64, verbose_name='№ заказ-наряда')),
                ('order_date', models.DateField(verbose_name='Дата заказ-наряда')),
            ],
            options={
                'verbose_name': 'ТО машины',
            },
        ),
        migrations.DeleteModel(
            name='Recipes',
        ),
        migrations.AddField(
            model_name='complaints',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.machine', verbose_name='Машина'),
        ),
        migrations.AddField(
            model_name='machine',
            name='drive_axle_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='drive_axle_models', to='App.referencebooks', verbose_name='Модель ведущего моста'),
        ),
        migrations.AddField(
            model_name='machine',
            name='engine_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='engine_models', to='App.referencebooks', verbose_name='Модель двигателя'),
        ),
        migrations.AddField(
            model_name='machine',
            name='guiding_bridge_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='guiding_bridge_models', to='App.referencebooks', verbose_name='Модель управляемого моста'),
        ),
        migrations.AddField(
            model_name='machine',
            name='machine_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='machine_models', to='App.referencebooks', verbose_name='Модель техники'),
        ),
        migrations.AddField(
            model_name='machine',
            name='transmission_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transmission_models', to='App.referencebooks', verbose_name='Модель трансмиссии'),
        ),
        migrations.AddField(
            model_name='complaints',
            name='machine_failure_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='machine_failure_nodes', to='App.referencebooks', verbose_name='Узел отказа'),
        ),
        migrations.AddField(
            model_name='complaints',
            name='method_restoring',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='methods_restoring', to='App.referencebooks', verbose_name='Способ восстановления'),
        ),
        migrations.AddField(
            model_name='machine',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='service_companies', to='App.servicecompany', verbose_name='Сервисная компания'),
        ),
        migrations.AddField(
            model_name='techmaintenance',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.machine', verbose_name='Машина'),
        ),
        migrations.AddField(
            model_name='techmaintenance',
            name='organization_maintenance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='App.referencebooks', verbose_name='Организация, проводившая ТО'),
        ),
        migrations.AddField(
            model_name='techmaintenance',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='App.servicecompany', verbose_name='Сервисная компания'),
        ),
        migrations.AddField(
            model_name='techmaintenance',
            name='type_maintenance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='type_maintenance', to='App.referencebooks', verbose_name='Вид ТО'),
        ),
    ]
