# Generated by Django 5.1.3 on 2025-02-24 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_complaints_options_alter_machine_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AddField(
            model_name='complaints',
            name='service_company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='App.servicecompany', verbose_name='Сервисная компания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='machine',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='App.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='delivery_agreement',
            field=models.CharField(max_length=32, unique=True, verbose_name='Договор поставки №, дата'),
        ),
    ]
